version: "3"
services:
  redis:
    hostname: redis
    image: redis:5.0.4
    volumes:
      - ./redis/datadir:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: redis-server --requirepass 123456
    ports:
      - 6380:6379
  php:
    hostname: php
    image: php:7.2.24-fpm
    networks:
      - lnmp
    volumes:
      - ./wwwroot:/wwwroot
    environment: 
      - APP_ENV=testing
      - TZ=Asia/Shanghai
  nginx:
    hostname: nginx
    image: nginx:1.16.1
    networks:
      - lnmp
    ports:
      - 80:80
    volumes:
      - ./wwwroot:/wwwroot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment: 
      - TZ=Asia/Shanghai
    links:
      - php
  mysql:
    hostname: mysql
    image: mysql:5.6
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3307:3306
    networks:
      - lnmp
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
networks:
  lnmp:
